[package]
name = "raphael-data-updater"
edition = "2024"

[lints]
workspace = true

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
reqwest = "0.12.24"
json = "0.12.4"
log = { workspace = true }
env_logger = "0.11.8"
