on: pull_request

jobs:
  bench_solver:
    runs-on: self-hosted
    name: Benchmark
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
      - name: Run benchmark
        run: echo Benchmarking \`${{ github.base_ref }}\` > message.txt && ./bench-solver.sh >> message.txt

      - name: Checkout feature branch
        uses: actions/checkout@v3
      - name: Run benchmark
        run: echo Benchmarking \`${{ github.ref }}\` >> message.txt && ./bench-solver.sh >> message.txt

      - name: Add result as comment on PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: benchmark
          file-path: message.txt
