name: Check commit

on:
  push:
    branches: ["preview", "main"]
  pull_request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check that workspace builds with MSRV
        run: cargo +1.89.0 check --workspace

      - name: Check for clippy warnings when building native version
        run: cargo clippy --workspace

      - name: Install required components for web version
        run: rustup component add --toolchain nightly clippy rust-src
      - name: Check for clippy warnings when building web version
        run: BASE_URL=localhost cargo +nightly clippy --config ./.cargo/config_wasm.toml

  check-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check that workspace builds with MSRV
        run: cargo +1.89.0 check --workspace

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run all tests
        run: cargo test --verbose --workspace
